version: '3.7'

services:
  training:
    image: microservices-ia/training-microservice
    build: ./services/training-microservice
    container_name: microservices-ia-training-microservice
    ports:
      - "5000:5000"
    volumes:
      - ./services/training-microservice:/app

  prediction:
    image: microservices-ia/prediction-microservice
    build: ./services/prediction-microservice
    container_name: microservices-ia-prediction-microservice
    ports:
      - "5001:5000"
    volumes:
      - ./services/prediction-microservice:/app
